# Generated by Django 2.2.3 on 2019-07-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_registration', models.CharField(max_length=15)),
                ('cc_begin', models.PositiveSmallIntegerField()),
                ('cc_end', models.PositiveSmallIntegerField()),
                ('_2070', models.IntegerField()),
                ('_2071', models.IntegerField()),
                ('_2072', models.IntegerField()),
                ('_2073', models.IntegerField()),
                ('_2074', models.IntegerField()),
                ('_2075', models.IntegerField()),
            ],
        ),
    ]
