# Generated by Django 2.2.3 on 2019-07-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax_calculator', '0002_smallvehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='LargeVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_registration', models.CharField(max_length=15)),
                ('vehicle_type', models.CharField(max_length=15)),
                ('_2070', models.IntegerField()),
                ('_2071', models.IntegerField()),
                ('_2072', models.IntegerField()),
                ('_2073', models.IntegerField()),
                ('_2074', models.IntegerField()),
                ('_2075', models.IntegerField()),
            ],
        ),
    ]
